package com.Security.Manager;
//Полномочия
public enum ActionType
{
    WRITE_COMMENTS,WRITE_POSTS,
    DELETE_YOUR_POST,DELETE_YOUR_COMMENTS ,
    DELETE_ALIEN_POST,DELETE_ALIEN_COMMENTS,
    UPDATE_YOUR_POST,UPDATE_YOUR_COMMENTS ,
    UPDATE_ALIEN_POST,UPDATE_ALIEN_COMMENTS,
    UPDATE_ALIEN_USER, UPDATE_YOUR_USER,
    DELETE_ALIEN_USER, DELETE_YOUR_USER
}
